### ISSUE TITLE
이미지를 못찾고있습니다.

### ISSUE THREAD

**Issue by changicho** [woowa-techcamp-2020/bmart-10#112]
```text
GET http://3.35.51.138/asset/img/1585893088954l0.jpg 404 (Not Found)
```

자꾸 이 에러가 발생하네요

**Comment by brightchul** [comment]
api 개발 전에 한거라 의 테스트 용으로 해놓은  img 디렉토리 안의 이미지가 일부 누락되어서 그렇습니다. 
디비 데이터를 받아서 이미지 받는 것으로 하면 수정 될 것입니다. 

해당 사항 수정되면 이슈 연결해 놓겠습니다.

**Comment by brightchul** [comment]
해당 부분에서 s3 서버의 이미지와 연결시키면서 해당 문제는 수정되었습니다.
