### ISSUE TITLE
메인 페이지에서 필요한 API 개발

### ISSUE THREAD

**Issue by sss5793** [woowa-techcamp-2020/bmart-10#144]
> 이슈 요약(선택)

기한 : 2020.08.27

예상 작업 시간 : 2시간

실제 작업 시간 : 0시간

### 작업 내용

- [x] 사용자를 위해 준비한 상품 API 구현 (사용자를 위한 상품 10개)
- [x] 새로 나왔어요 API 구현 (새로 나온 상품 기준 10개)
- [x] 요즘 잘팔려요 API 구현 (잘 팔린 순서 기준 10개)

**Comment by brightchul** [comment]
장바구니 하느라 바쁘실거 같으니
위의 3가지는 제가 하도록 하겠습니다.
